### ISSUE TITLE
Cannot connect to server on localhost

### ISSUE THREAD

**Issue by WilliamDann** [WilliamDann/minesweeper-royale#15]
When running the server on localhost the server cannot connect via WebSockets. This is because of the change on line 23 of server/app.js in 4c2a0c7c47d27b297221bb26ec307099cbb96c08, it was localhost now it is 10.0.0.122. What is the reason for this change?

**Comment by WilliamDann** [comment]
@ottomated

**Comment by ottomated** [comment]
In production, this will need to be dynamic in order for players to connect to the website. For now it can be localhost, I changed it to 10.0.0.122 in order to test LAN networking at CodeDay.

**Comment by WilliamDann** [comment]
What if there was a command line parameter for it? You could specify `--hostname` or something like that when you run the program to set it.

I have already written this code If it sounds like a good idea.
