### ISSUE TITLE
Replacing start tile with a zero causes bombs to be shown

### ISSUE THREAD

**Issue by WilliamDann** [WilliamDann/minesweeper-royale#8]
When a user clicks on a mine at the beginning of the game, the mine is replaced with a zero. There is a problem with this: if another bomb is adjacent, calling it a zero is incorrect. The click algorithm is tricked into revealing the adjacent bomb because there is a zero square next to it. The image below demonstrates this.

![image](https://user-images.githubusercontent.com/25412286/53770391-b89e2f80-3e93-11e9-8510-c42a57214fac.png)

The zero needs to either change to the correct number given the surrounding bombs or have the bombs around be changed to a correct number.

**Comment by ottomated** [comment]
Looking at the code, this is probably because I was treating getSurrounding as if it returned Tile objects.
